"""create categories and products

Revision ID: 3c8494895f77
Revises: 8c84ff0fc322
Create Date: 2026-07-07 18:08:44.225588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8494895f77'
down_revision: Union[str, Sequence[str], None] = '8c84ff0fc322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:

    op.create_table(
        'categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.create_table(
        'products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'available',
                'out_of_stock',
                'on_the_way',
                name='productstatus'
            ),
            nullable=False
        ),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['categories.id']
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     product_status = sa.Enum(
#         'available',
#         'out_of_stock',
#         'on_the_way',
#         name='productstatus',
#         create_type=False
#     )
#
#     product_status.create(
#         op.get_bind(),
#         checkfirst=True
#     )
#
#     op.create_table('categories',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.Column('description', sa.String(), nullable=True),
#     sa.PrimaryKeyConstraint('id'),
#     sa.UniqueConstraint('name')
#     )
#     op.create_table('products',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.Column('description', sa.String(), nullable=True),
#     sa.Column(
#         'status',
#         product_status,
#         nullable=False
#     ),
#     sa.Column('category_id', sa.Integer(), nullable=False),
#     sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
#     sa.PrimaryKeyConstraint('id'),
#     sa.UniqueConstraint('name')
#     )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('categories')
    op.execute("DROP TYPE IF EXISTS productstatus")
    # ### end Alembic commands ###
