"""add a column quantity for products

Revision ID: 8949a79a3c4b
Revises: ffe51c03d2bd
Create Date: 2026-07-08 12:42:36.372733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8949a79a3c4b'
down_revision: Union[str, Sequence[str], None] = 'ffe51c03d2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
